In [1]:
# 定义并加载奖励模型
import torch
from torch import nn
import numpy as np
from transformers import AutoModelForCausalLM

class RewardHead(nn.Module):
    def __init__(self, config):
        super().__init__()
        # llm最后输出的隐藏层的维度
        self.hidden_size = config.hidden_size
        # 线性层用来对llm最后输出的隐藏层给奖励
        self.reward = nn.Linear(self.hidden_size, 1)
        self._post_init()

    def _post_init(self):
        # 使用正态分布初始化权重
        nn.init.normal_(
            self.reward.weight,
            std=(1.0 / np.sqrt(self.hidden_size + 1))
        )
        # 将偏置初始化为0
        nn.init.zeros_(self.reward.bias)

    def forward(self, hidden_states):
        # 给出奖励
        return self.reward(hidden_states)

class GPT2RewardHead(nn.Module):
    def __init__(self, model_name):
        super().__init__()
        self.llm = AutoModelForCausalLM.from_pretrained(model_name)
        self.reward_head = RewardHead(self.llm.config)

    def forward(self, input_ids, attention_mask):
        transformer_outputs = self.llm.forward(
            input_ids=input_ids,
            attention_mask=attention_mask,
            output_hidden_states=True
        )
        last_hidden_state = transformer_outputs.hidden_states[-1]
        # 给出奖励
        reward = self.reward_head(last_hidden_state).squeeze(-1)
        # sigmoid用来将奖励搞到(0,1)范围内
        return torch.sigmoid(reward)

/opt/anaconda3/envs/rlhf/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
model_name = "/Users/zhangyf/llm/gpt2"
reward_model = GPT2RewardHead(model_name)
reward_model.load_state_dict(torch.load("reward_model.pt", map_location='cpu'))

<All keys matched successfully>

In [3]:
# 定义价值函数头
import torch
from typing import Optional
from torch import nn
import numpy as np
from transformers import AutoModelForCausalLM

class ValueHead(nn.Module):
    """
    ValueHead类为GPT2实现了一个“头”，会为输出的每个token返回一个标量值
    标量值就是这个token的价值，ValueHead就是评论家。
    """
    def __init__(self, config):
        super().__init__()
        # llm最后输出的隐藏层的维度
        self.hidden_size = config.hidden_size
        # 价值网络的输出是标量
        self.value = nn.Linear(self.hidden_size, 1)
        self._post_init()

    def _post_init(self):
        nn.init.normal_(
            self.value.weight,
            std=(1.0 / np.sqrt(self.hidden_size + 1))
        )
        nn.init.zeros_(self.value.bias)

    def forward(self, hidden_states):
        output = hidden_states
        return self.value(output)

In [4]:
# 策略模型和价值头结合
class ModelForCausalLMWithValueHead(nn.Module):
    """
    GPT2模型+一个价值头
    """
    def __init__(self, model_path):
        super().__init__()
        # 这个要初始化为我们微调出来的gpt2-sft模型
        # actor演员模型：策略模型
        self.llm = AutoModelForCausalLM.from_pretrained(model_path)
        # 添加价值头
        # critic评论家模型：价值函数模型，价值头
        self.v_head = ValueHead(self.llm.config)

    def forward(
        self,
        input_ids,
        attention_mask,
    ) -> Optional[torch.FloatTensor]:
        # gpt2-sft模型的输出
        transformer_outputs = self.llm.forward(
            input_ids,
            attention_mask=attention_mask,
            output_hidden_states = True,
        )
        # 输出的token的概率分布，维度为 `vocab_size`
        lm_logits = transformer_outputs.logits
        # 获取最后一层隐藏层
        last_hidden_state = transformer_outputs.hidden_states[-1]

        # 评估token的价值，评估的是最后一层隐藏层的价值
        value = self.v_head(last_hidden_state).squeeze(-1)
        # 返回输出的token的logits和token的价值
        return lm_logits, value

    def generate(self, *args, **kwargs):
        return self.llm.generate(*args, **kwargs)

In [5]:
# 要训练的策略模型
model_path = '/Users/zhangyf/llm/gpt2-sft'
model = ModelForCausalLMWithValueHead(model_path)

In [6]:
# 加载数据
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained(model_path)
tokenizer.pad_token = tokenizer.eos_token

from datasets import load_dataset
dataset = load_dataset("./sst2")
# print(dataset)
ds_train, ds_val = dataset['train'], dataset['validation']

Generating test split: 100%|██████████| 1821/1821 [00:00<00:00, 763553.69 examples/s]


In [7]:
# 过滤掉长度小于8的样本
print(len(ds_train))
ds_train = ds_train.filter(lambda x: len(x['sentence'].split(' ')) > 8)
ds_val = ds_val.filter(lambda x: len(x['sentence'].split(' ')) > 8)
print(len(ds_train))
print(len(ds_val))

67349


Filter:   0%|          | 0/67349 [00:00<?, ? examples/s]

Filter:   0%|          | 0/872 [00:00<?, ? examples/s]

31105
807


In [10]:
import random
input_min_token_length = 2
input_max_token_length = 8
input_token_length_range = list(range(
    input_min_token_length,
    input_max_token_length))
print(input_token_length_range)
print(random.choice(input_token_length_range))

[2, 3, 4, 5, 6, 7]
6


In [11]:
def tokenize(sample):
    input_size = random.choice(input_token_length_range)
    sample['input_ids'] = tokenizer.encode(sample['sentence'])[:input_size]
    sample['attention_mask'] = [1] * len(sample['input_ids'])
    sample['query'] = tokenizer.decode(sample['input_ids'])
    return sample

map_kwargs = {
    "batched": False,
    "remove_columns": ['idx', 'sentence', 'label']
}

tokenized_dataset_train = ds_train.map(tokenize, **map_kwargs)
tokenized_dataset_val = ds_val.map(tokenize, **map_kwargs)

Map:   0%|          | 0/31105 [00:00<?, ? examples/s]

Map:   0%|          | 0/807 [00:00<?, ? examples/s]

In [12]:
tokenized_dataset_train[48]

{'input_ids': [19188, 423, 8288, 340],
 'attention_mask': [1, 1, 1, 1],
 'query': 'would have liked it'}

In [13]:
tokenized_dataset_train.set_format(type='torch')
tokenized_dataset_val.set_format(type='torch')

print(tokenized_dataset_train[48])

{'input_ids': tensor([19188,   423,  8288,   340]), 'attention_mask': tensor([1, 1, 1, 1]), 'query': 'would have liked it'}


In [14]:
REWARD_TOKEN_ID = tokenizer.eos_token_id

In [15]:
from torch.utils.data import DataLoader

batch_size = 32

def collator(batch):
    return dict((key, [d[key] for d in batch]) for key in batch[0])

train_dataloader = DataLoader(tokenized_dataset_train, batch_size=batch_size, collate_fn=collator, shuffle=True)
val_dataloader = DataLoader(tokenized_dataset_val, batch_size=batch_size, collate_fn=collator, shuffle=True)

batch = next(iter(train_dataloader))
print(batch)

{'input_ids': [tensor([ 338, 3446,  644,  777,  734,  661]), tensor([3919,  258,  468,  925,  257, 7709]), tensor([22850,   597,  8674,   286,  7401,   561]), tensor([   64, 13393]), tensor([ 259,  867, 2842,  257]), tensor([   83, 14992,   284,   787]), tensor([ 1169, 13289]), tensor([1996,   82]), tensor([1477,  403, 7285, 1312,   86, 1872]), tensor([1169, 1708, 1243]), tensor([  272, 17774,  6594,   837,  3805,   867]), tensor([ 533, 1913,  837]), tensor([   7,  256, 1267]), tensor([ 259,  777, 3435]), tensor([   11,   428, 32251,   318,  1165,  7812]), tensor([5036, 1424,  355, 6228,  355,  262,  629]), tensor([10919,  2482,   318,   262,  1266]), tensor([  338,   635,   555, 24194]), tensor([ 1169, 48718,  3437,   468,  2900,   503,  3016]), tensor([10197,   355,   262,  4293,   286]), tensor([31712,   351,   262]), tensor([16794,   514]), tensor([ 1455,    84,   528, 18811]), tensor([1462,  307,  262, 3807,  705]), tensor([  986,   663, 26322,  2181,  3004, 15174,   514]), tensor

In [16]:
output_min_length = 5
output_max_length = 16

# https://huggingface.co/docs/trl/how_to_train#how-to-generate-text-for-training
# gpt2-sft输出的配置
# - 模型会从整个词汇表中按照原始概率分布进行采样
# - 每个词被选中的概率完全由模型的原始输出决定
generation_kwargs = {
    "min_length": -1,
    "top_k": 0.0, # 所有词汇表中的词都可能被选中
    "top_p": 1.0, # 包含整个概率分布
    "do_sample": True,
    "pad_token_id": tokenizer.pad_token_id
}

In [17]:
new_tokens = random.choice(list(range(output_min_length, output_max_length)))
generation_kwargs["max_new_tokens"] = new_tokens
sample = tokenizer('Hi, this')
print(sample)
print(generation_kwargs)

{'input_ids': [17250, 11, 428], 'attention_mask': [1, 1, 1]}
{'min_length': -1, 'top_k': 0.0, 'top_p': 1.0, 'do_sample': True, 'pad_token_id': 50256, 'max_new_tokens': 12}


In [18]:
query_response = model.generate(
    input_ids=torch.tensor(sample['input_ids']).unsqueeze(0),
    attention_mask=torch.tensor(sample['attention_mask']).unsqueeze(0),
    **generation_kwargs
).squeeze(0)
print(query_response)

tensor([17250,    11,   428,   318,  1016,   284,   307,  1223,   922,   220,
          220,   220,   220, 28251,   220])


In [19]:
print(tokenizer.decode(query_response))

Hi, this is going to be something good     endeavor 


In [20]:
new_tokens

12

In [22]:
# 测试一下奖励模型，能拿到多少奖励
with torch.no_grad():
    query_response_score = torch.cat([
        query_response,
        torch.tensor([REWARD_TOKEN_ID])])
    attention_mask = torch.ones_like(query_response_score, dtype=torch.long)
    score = reward_model(
        query_response_score.unsqueeze(0),
        attention_mask.unsqueeze(0)
    )
    print(score)
    score = score.squeeze(0)[-1]
print(score)

tensor([[0.8801, 0.8562, 0.8565, 0.7811, 0.9256, 0.6584, 0.7812, 0.6571, 0.9824,
         0.9965, 0.9970, 0.9973, 0.9979, 0.9931, 0.9962, 0.9987]])
tensor(0.9987)


In [23]:
query_tensors = batch['input_ids']
query_attention_masks = batch['attention_mask']
print(len(query_tensors),len(query_attention_masks))

32 32


In [25]:
# 生成一批测试数据看一下
device = torch.device("mps" if torch.mps.is_available() else "cpu")
model = model.to(device)
reward_model = reward_model.to(device)

query_tensors = batch['input_ids']
query_attention_masks = batch['attention_mask']

response_tensors = [] # 补全的张量
query_response_tensors = [] # 提示词+补全 的张量
score_tensors = [] # 奖励模型给的分数的张量

for i, query in enumerate(query_tensors):
    query = query.to(device)
    query_attention_mask = query_attention_masks[i].to(device)
    new_tokens = random.choice(list(range(output_min_length, output_max_length)))
    generation_kwargs["max_new_tokens"] = new_tokens
    query_response = model.generate(
        input_ids=query.unsqueeze(0),
        attention_mask=query_attention_mask.unsqueeze(0),
        **generation_kwargs
    ).squeeze(0)

    response_len = len(query_response) - len(query)
    response_tensors.append(query_response[-response_len:])
    query_response_tensors.append(query_response)

    with torch.no_grad():
        query_response_score = torch.cat([query_response, torch.tensor([REWARD_TOKEN_ID]).to(device)])
        attention_mask = torch.ones_like(query_response_score, dtype=torch.long)
        score = reward_model(
            query_response_score.unsqueeze(0),
            attention_mask.unsqueeze(0)
        ).squeeze(0)[-1]
        score = 2 * (score - 0.5)
    score_tensors.append(score)

batch["response"] = [tokenizer.decode(response) for response in query_response_tensors]
from pprint import pprint
pprint(batch['response'])
# 奖励分数
pprint(score_tensors)

["'s exactly what these two people need to find each other   ",
 "nohe has made a decent horror flick - as far as i 've found",
 'why any actor of talent would ever work for an agency like this   ',
 'a stunning creation in aelica',
 'in many ways a zine .   ',
 "trying to make monty bear 's death comic",
 'the performances are often lush , ivan and silverstein are fascinating',
 'puts ( steven seagal',
 "shunji iwai 's dedication and sense of humor ian style ian bolado",
 "the following things were n't true :",
 'an entertaining ride , despite many flaws .          unrealistic ,',
 'are strong , ive seen more dragons than i ive seen these many ,',
 "( t ) icholson icholson 's latest feature",
 "in these characters you 're rooting for",
 ', this thriller is too loud and boisterous and too stupid if it',
 'feels as flat as the scapes of ( its ) subconscious',
 'what results is the best didacticism of recent memory .',
 "'s also uninspired , with scenes that don't add up to much .  ",
 '

In [48]:
from copy import deepcopy
# 冻结的参考模型
sft_model = deepcopy(model)

In [49]:
len(query_response_tensors)

32

In [50]:
from transformers import DataCollatorWithPadding
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

input_data = data_collator([
    {'input_ids': ids,
     'attention_mask': torch.ones_like(ids)} for ids in query_response_tensors
]).to(device)
print(input_data['input_ids'].shape)
print(input_data['attention_mask'].shape)

torch.Size([32, 22])
torch.Size([32, 22])


In [51]:
def compute_rewards(
    input_data,
    query_tensors,
    response_tensors,
    score_tensors
):
    with torch.no_grad():
        # 正在微调的模型所输出的token的logits和token的价值
        # 模型输出所有token的概率分布
        # logits.shape[32,22,50257],values.shape[32,22]
        logits, values = model(**input_data) # b, seq, vocab
        # 冻结的模型的输出和价值
        # ref_logits.shape[32,22,50257]
        ref_logits, _ = sft_model(**input_data)
        # 正在微调的模型的输出的对数概率[32,21,50257]
        logp = torch.nn.functional.log_softmax(logits[:, :-1, :], dim=-1)
        # 冻结的模型的输出的对数概率 b, seq , 50257。 [32,21,50257]
        ref_logp = torch.nn.functional.log_softmax(ref_logits[:, :-1, :], dim=-1)
        # 实际生成的token序列
        labels = input_data['input_ids'][:, 1:] # b, seq
        # 使用gather提取实际token的概率
        logp = torch.gather(
            logp,
            2,
            labels.unsqueeze(-1)
        ).squeeze(-1) # batch, seq
        ref_logp = torch.gather(
            ref_logp,
            2,
            labels.unsqueeze(-1)
        ).squeeze(-1) # batch, seq
        # kl散度,shape[32,21]
        kl = logp - ref_logp
        # kl散度的权重
        beta = 0.2
        # 最终奖励的计算shape[32,21]
        rewards = - beta * kl
        attention_mask = input_data['attention_mask']
        masks = torch.zeros_like(attention_mask[:, 1:])
        masks[:,:] = attention_mask[:, 1:]
        for j in range(len(query_tensors)):
            start = len(query_tensors[j]) - 1
            end = start + len(response_tensors[j])
            masks[j, :start] = 0
            masks[j, end:] = 0
            rewards[j, end - 1] += score_tensors[j]
            rewards[j, :] *= masks[j, :]
            values[j, :-1] *= masks[j, :]

    return logp, rewards, values[:, :-1], masks

In [52]:
score_tensors

[tensor(0.9460, device='mps:0'),
 tensor(0.6834, device='mps:0'),
 tensor(-0.9678, device='mps:0'),
 tensor(0.9933, device='mps:0'),
 tensor(0.4125, device='mps:0'),
 tensor(-0.5697, device='mps:0'),
 tensor(0.9995, device='mps:0'),
 tensor(0.8174, device='mps:0'),
 tensor(0.9951, device='mps:0'),
 tensor(-0.9966, device='mps:0'),
 tensor(0.9855, device='mps:0'),
 tensor(0.9841, device='mps:0'),
 tensor(0.9050, device='mps:0'),
 tensor(0.8399, device='mps:0'),
 tensor(-0.9996, device='mps:0'),
 tensor(-0.9991, device='mps:0'),
 tensor(0.9919, device='mps:0'),
 tensor(-0.9998, device='mps:0'),
 tensor(-0.9971, device='mps:0'),
 tensor(0.2916, device='mps:0'),
 tensor(0.9893, device='mps:0'),
 tensor(0.8594, device='mps:0'),
 tensor(0.9407, device='mps:0'),
 tensor(0.9826, device='mps:0'),
 tensor(-0.6785, device='mps:0'),
 tensor(-0.9938, device='mps:0'),
 tensor(-0.1950, device='mps:0'),
 tensor(-0.8641, device='mps:0'),
 tensor(0.9992, device='mps:0'),
 tensor(0.9781, device='mps:0'),

In [53]:
logprobs, rewards, values, masks = compute_rewards(
    input_data,
    query_tensors,
    response_tensors,
    score_tensors
)
print(rewards[0])
print(input_data['input_ids'][0])
print(input_data['attention_mask'][0])
print(masks[0])
print(values[0])
print(rewards.shape)
print(values.shape)
print(masks.shape)

tensor([0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 8.6173e-03,
        3.9769e-02, 9.1950e-03, 1.7422e-02, 1.1886e-04, 2.0017e-01, 5.2899e-03,
        9.4738e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00], device='mps:0')
tensor([  338,  3446,   644,   777,   734,   661,   761,   284,  1064,  1123,
          584,   220,   220,   220, 50256, 50256, 50256, 50256, 50256, 50256,
        50256, 50256], device='mps:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       device='mps:0')
tensor([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       device='mps:0')
tensor([-0.0000, -0.0000, -0.0000, -0.0000,  0.0000, -2.0779,  0.0874, -2.4765,
        -4.0814, -1.0521, -2.0755,  0.1735, -0.5004,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000], device='mps:0')
torch.Size([32, 21])
torch.Size([32, 21])
torch.Size([32, 21])


In [55]:
def masked_mean(values, mask):
    # 计算带掩码的平均值
    return (values * mask).sum() / mask.sum()

def masked_var(values, mask):
    # 计算带掩码的方差
    mean = masked_mean(values, mask)
    centred_values = values - mean
    return masked_mean(centred_values ** 2, mask)

def masked_whiten(values, mask):
    '''
    对数据进行带掩码的白化处理，
    让有效数据的方差变为1，但均值保持不变
    '''
    mean, var = masked_mean(values, mask), masked_var(values, mask)
    whitened = (values - mean) * torch.rsqrt(var + 1e-8)
    whitened += mean
    return whitened

def compute_advantage(rewards, values, masks):
    '''
    广义优势估计（GAE）
    '''
    lastgae = 0.0
    advantage_reversed = []
    seq_length = rewards.shape[-1]
    gamma, lam = 1.0, 0.95

    for t in reversed(range(seq_length)):
        nextvalues = values[:, t + 1] if t < seq_length - 1 else 0.0
        delta = rewards[:, t] + gamma * nextvalues - values[:, t]
        lastgae = delta + gamma * lam * lastgae
        advantage_reversed.append(lastgae)
    advantages = torch.stack(advantage_reversed[::-1], dim=1)
    advantages = masked_whiten(advantages, masks)

    returns = advantages + values
    return advantages, returns

In [56]:
advantages, returns = compute_advantage(rewards, values, masks)
print(advantages[0])
print(returns[0])
print(values[0])

tensor([1.8405, 1.8457, 1.8513, 1.8571, 1.8633, 2.6995, 1.8820, 2.8972, 3.5953,
        2.4764, 2.9238, 2.0082, 2.2892, 1.7401, 1.7401, 1.7401, 1.7401, 1.7401,
        1.7401, 1.7401, 1.7401], device='mps:0')
tensor([ 1.8405,  1.8457,  1.8513,  1.8571,  1.8633,  0.6216,  1.9693,  0.4207,
        -0.4861,  1.4244,  0.8483,  2.1816,  1.7888,  1.7401,  1.7401,  1.7401,
         1.7401,  1.7401,  1.7401,  1.7401,  1.7401], device='mps:0')
tensor([-0.0000, -0.0000, -0.0000, -0.0000,  0.0000, -2.0779,  0.0874, -2.4765,
        -4.0814, -1.0521, -2.0755,  0.1735, -0.5004,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000], device='mps:0')


In [57]:
# 小批次PPO训练
learning_rate = 1e-5
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)
# 随机排列一下各个批次大小
np.random.permutation(batch_size)

array([ 0, 27, 22,  4, 28, 29, 25,  7, 13, 12, 31, 26, 20, 30,  6, 15, 16,
       19, 14, 24,  2,  1, 17, 10, 21, 23,  3, 18,  5,  8,  9, 11])

In [59]:
# 最小的批次大小
mini_batch_size = 4
# 训练 4 个 epoch
ppo_epochs = 4
# ε = 0.2
cliprange_ratio = 0.2

v_loss_coeff = 0.1
# 比例的阈值
ratio_threshold = 10

def compute_loss(
    old_logprobs, # 冻结的一份概率
    values, # 价值
    logprobs, # 正在微调的模型输出的对数概率
    vpreds, # 预测的价值
    masks, # 掩码
    advantages, # 广义优势估计
    returns # 回报
):
    # 比率
    ratio = torch.exp(logprobs - old_logprobs)
    # 比率 * 广义优势估计
    pg_loss1 = - ratio * advantages
    # clip(比率，1-ϵ,1+ϵ) * 广义优势估计
    pg_loss2 = - torch.clamp(
        ratio,
        1 - cliprange_ratio,
        1 + cliprange_ratio
    ) * advantages
    # 策略（gpt2-sft）的损失
    pg_loss = masked_mean(torch.max(pg_loss1, pg_loss2), masks)
    # 价值网络（价值头）的损失，mse
    v_loss = masked_mean((vpreds - returns) ** 2, masks)
    # 由于 正在微调的模型 = gpt2-sft + value_head
    # 总的损失 = 策略网络的损失 + 0.1 * 价值网络的损失
    loss = pg_loss + v_loss_coeff * v_loss
    # 计算平均比率
    avg_ratio = masked_mean(ratio, masks)
    # 这一步不在ppo公式中
    # 如果平均比率 > 10
    if avg_ratio > ratio_threshold:
        pg_loss = pg_loss * 0.0
        v_loss = v_loss * 0.0
        loss = loss * 0.0

    return loss, v_loss

def mini_batch_train():
    for ep in range(ppo_epochs):
        batch_inds = np.random.permutation(batch_size)
        # range(0, 32, 4)
        i = 0
        for start in range(0, batch_size, mini_batch_size):
            # start = 0; end = 4
            end = start + mini_batch_size
            mini_batch_inds = batch_inds[start:end]

            mb_model_inputs = {
                'input_ids': input_data \
                    ['input_ids'] \
                    [mini_batch_inds],
                'attention_mask': input_data \
                    ['attention_mask'] \
                    [mini_batch_inds]
            }
            # 模型的输出是token的logits和value
            mb_logits, mb_vpreds = model(**mb_model_inputs)
            # 去掉最后一个token
            mb_logits = torch.nn.functional.log_softmax(
                mb_logits[:, :-1, :],
                dim=-1
            )
            # 取出真实标签对应的概率
            mb_logprobs = torch.gather(
                mb_logits,
                2,
                mb_model_inputs['input_ids'][:, 1:].unsqueeze(-1)
            ).squeeze(-1)

            loss, loss_v = compute_loss(
                logprobs[mini_batch_inds],
                values[mini_batch_inds],
                mb_logprobs,
                mb_vpreds[:, :-1],
                masks[mini_batch_inds],
                advantages[mini_batch_inds],
                returns[mini_batch_inds]
            )

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            i += 1
            print(f'loss/total_{(ep+1) * (i)}', loss.item())
    print('mini-batch training finished')

In [50]:
mini_batch_train()

loss/total 0.0630950778722763
loss/total 0.08078935742378235
loss/total -0.11473453044891357
loss/total 0.4748775362968445
loss/total 0.10602464526891708
loss/total 0.1982056200504303
loss/total 0.15830230712890625
loss/total -0.307778000831604
loss/total 0.24319370090961456
loss/total -0.043497439473867416
loss/total -0.0032646358013153076
loss/total -0.09986380487680435
loss/total -0.3570232689380646
loss/total -0.10384085774421692
loss/total 0.2232135683298111
loss/total -0.11403181403875351
loss/total -0.0358172170817852
loss/total -0.232884019613266
loss/total -0.10820959508419037
loss/total 0.40299054980278015
loss/total -0.12002972513437271
loss/total -0.11467400938272476
loss/total -0.513324499130249
loss/total -0.08656121790409088
loss/total 0.13452798128128052
loss/total -0.12799489498138428
loss/total -0.3488343060016632
loss/total -0.1875464767217636
loss/total -0.3424496054649353
loss/total -0.1724880486726761
loss/total -0.038934655487537384
loss/total 0.30629023909568787

In [60]:
# 正式开始训练
num_epochs = 1

for epoch in range(num_epochs):
    for batch in train_dataloader:
        # 生成补全内容（回复）
        query_tensors = batch['input_ids'] # 提示词的张量
        query_attention_masks = batch['attention_mask']

        response_tensors = [] # 补全的张量
        query_response_tensors = [] # 提示词+补全的张量
        score_tensors = [] # 分数的张量

        for i, query in enumerate(query_tensors):
            query = query.to(device)
            query_attention_mask = query_attention_masks[i].to(device)
            # 随机挑一个补全的长度
            new_tokens = random.choice(list(range(
                output_min_length,
                output_max_length)))
            # 设置补全长度属性
            generation_kwargs["max_new_tokens"] = new_tokens
            # 提示词 + 补全
            query_response = model.generate(
                input_ids=query.unsqueeze(0),
                attention_mask=query_attention_mask.unsqueeze(0),
                **generation_kwargs
            ).squeeze(0)
            # 补全的长度
            response_len = len(query_response) - len(query)
            # 补全的张量
            response_tensors.append(query_response[-response_len:])
            query_response_tensors.append(query_response)

            with torch.no_grad():
                # 提示词 + 补全 + reward_token
                query_response_score = torch.cat([
                    query_response,
                    torch.tensor([REWARD_TOKEN_ID]).to(device)])
                attention_mask = torch.ones_like(
                    query_response_score,
                    dtype=torch.long)
                # 奖励模型的评分
                score = reward_model(
                    query_response_score.unsqueeze(0),
                    attention_mask.unsqueeze(0)
                ).squeeze(0)[-1]
                # 将奖励模型的评分从(0,1)缩放到(-1,1)
                score = 2 * (score - 0.5)
            score_tensors.append(score)

        input_data = data_collator([
            {
                'input_ids': ids,
                'attention_mask': torch.ones_like(ids)
            }
            for ids in query_response_tensors
        ]).to(device)

        # 奖励和优势
        logprobs, rewards, values, masks = compute_rewards(
            input_data,
            query_tensors,
            response_tensors,
            score_tensors
        )
        advantages, returns = compute_advantage(rewards, values, masks)

        # 小批次训练
        mini_batch_train()
    print(f'epoch {epoch + 1} finished')

loss/total_1 -0.5186878442764282
loss/total_2 -0.5478278398513794


KeyboardInterrupt: 

In [54]:
print(len(tokenized_dataset_val))
val_gen_lengths = [0] * len(tokenized_dataset_val)
for i in range(len(tokenized_dataset_val)):
    val_gen_lengths[i] = random.choice(list(range(
        output_min_length,
        output_max_length)))
val_gen_lengths[:10]

807


[9, 8, 8, 7, 8, 14, 9, 5, 13, 15]

In [55]:
def validate():
    scores = []
    for b, batch in enumerate(val_dataloader):
        # 生成补全内容
        query_tensors = batch['input_ids']
        query_attention_masks = batch['attention_mask']
        for i, query in enumerate(query_tensors):
            query = query.to(device)
            query_attention_mask = query_attention_masks[i].to(device)
            new_tokens = val_gen_lengths[b * len(query_tensors) + i]
            generation_kwargs["max_new_tokens"] = new_tokens
            query_response = model.generate(
                input_ids=query.unsqueeze(0),
                attention_mask=query_attention_mask.unsqueeze(0),
                **generation_kwargs
            ).squeeze(0)
            query_response_score = torch.cat([
                query_response,
                torch.tensor([REWARD_TOKEN_ID]).to(device)])
            attention_mask = torch.ones_like(
                query_response_score, dtype=torch.long)
            score = reward_model(
                query_response_score.unsqueeze(0),
                attention_mask.unsqueeze(0)
            ).squeeze(0)[-1]
            score = 2 * (score - 0.5)
            scores.append(score.item())
    print('平均分数:', sum(scores) / len(scores))

In [57]:
validate()

平均分数: 0.8099561136451352


In [58]:
# 保存模型
torch.save(model.state_dict(), 'gpt2-ppo.pt')

In [60]:
# 测试一下gpt2-sft模型的输出
model_path = '/Users/zhangyf/llm/gpt2-sft'
model = ModelForCausalLMWithValueHead(model_path).to(device)
validate()

平均分数: 0.16474913472432037
